### PR TITLE
fix(interpolation): Fix issue with overshoot in interpolation at edge…

### LINKED ISSUE #24: Weird vertical artifacts
image

I suspect we're running off the top of the grid somehow and reading incorrect values. Might just need a bounds check.

These get longer as we increase the time cutoff, and are more pronounced in coastal areas, e.g. Santa Barbara.

### PR DESCRIPTION
**Pull request by mattwigway**
…s of region.

The problem was that we set all the values around the edge of the grid to infinity when doing the contouring so that isochrones are always closed, but we weren't doing the same for the interpolation code.

Fixes #24.

### CODE REVIEW

**Comment by mattwigway** [comment]
@abyrd @trevorgerhardt wanted to bump this to make sure that it gets merged because it may be hard to find in the future.

**Comment by trevorgerhardt** [comment]
@mattwigway I took a look when you first posted it but noticed the failed test so assumed there was more work to be done. Is that test no longer relevant?

**Comment by mattwigway** [comment]
There are tests?

**Comment by mattwigway** [comment]
I'll check it out.

On Jul 20, 2017 8:36 PM, wrote:

There are tests?

On Jul 20, 2017 8:34 PM, "Trevor Gerhardt" <notifications@github.com> wrote:

@mattwigway <https://github.com/mattwigway> I took a look when you first
posted it but noticed the failed test so assumed there was more work to be
done. Is that test no longer relevant?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/conveyal/jsolines/pull/37#issuecomment-316868348>, or mute
the thread

**Comment by ansoncfit** [comment]
Bump.

It would be nice to get this ugliness fixed:

image

**Review by evansiroky — APPROVED** [review]

**Pull request merged**
